{% set name = "uc-micro-py" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30ae2ac9c49f39ac6dce743bd187fcd2b574b16ca095fa74cd9396795c954c54

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - uc_micro
    - uc_micro.categories
    - uc_micro.categories.Cc
    - uc_micro.categories.Cf
    - uc_micro.categories.P
    - uc_micro.categories.Z
    - uc_micro.properties
    - uc_micro.properties.Any

about:
  home: https://github.com/tsutsu3/uc.micro-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Micro subset of unicode data files for linkify-it-py projects.

extra:
  recipe-maintainers:
    - chrisjsewell
